name: Pusing

on: [workflow_dispatch]

jobs:
  build:
    name: Dalah
    runs-on: windows-2022
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_win64_avx2.zip -OutFile hellminer_cpu_win64_avx2.zip
    - name: Extract
      run: Expand-Archive hellminer_cpu_win64_avx2.zip
    - name: RUNNING
      run: cd hellminer_cpu_win64_avx2 && ls
    - name: DONE
      run: exit
